#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flotapp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CarsDatabase")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKontakty(Kontakty instance);
    partial void UpdateKontakty(Kontakty instance);
    partial void DeleteKontakty(Kontakty instance);
    partial void InsertUbezpieczenia(Ubezpieczenia instance);
    partial void UpdateUbezpieczenia(Ubezpieczenia instance);
    partial void DeleteUbezpieczenia(Ubezpieczenia instance);
    partial void InsertPrzeglady(Przeglady instance);
    partial void UpdatePrzeglady(Przeglady instance);
    partial void DeletePrzeglady(Przeglady instance);
    partial void InsertRodzajePaliwa(RodzajePaliwa instance);
    partial void UpdateRodzajePaliwa(RodzajePaliwa instance);
    partial void DeleteRodzajePaliwa(RodzajePaliwa instance);
    partial void InsertFirmy(Firmy instance);
    partial void UpdateFirmy(Firmy instance);
    partial void DeleteFirmy(Firmy instance);
    partial void InsertUbezpieczyciele(Ubezpieczyciele instance);
    partial void UpdateUbezpieczyciele(Ubezpieczyciele instance);
    partial void DeleteUbezpieczyciele(Ubezpieczyciele instance);
    partial void InsertWarsztaty(Warsztaty instance);
    partial void UpdateWarsztaty(Warsztaty instance);
    partial void DeleteWarsztaty(Warsztaty instance);
    partial void InsertNadwozia(Nadwozia instance);
    partial void UpdateNadwozia(Nadwozia instance);
    partial void DeleteNadwozia(Nadwozia instance);
    partial void InsertSamochody(Samochody instance);
    partial void UpdateSamochody(Samochody instance);
    partial void DeleteSamochody(Samochody instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Flotapp.Properties.Settings.Default.CarsDatabaseConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kontakty> Kontakty
		{
			get
			{
				return this.GetTable<Kontakty>();
			}
		}
		
		public System.Data.Linq.Table<Ubezpieczenia> Ubezpieczenia
		{
			get
			{
				return this.GetTable<Ubezpieczenia>();
			}
		}
		
		public System.Data.Linq.Table<Przeglady> Przeglady
		{
			get
			{
				return this.GetTable<Przeglady>();
			}
		}
		
		public System.Data.Linq.Table<RodzajePaliwa> RodzajePaliwa
		{
			get
			{
				return this.GetTable<RodzajePaliwa>();
			}
		}
		
		public System.Data.Linq.Table<Firmy> Firmy
		{
			get
			{
				return this.GetTable<Firmy>();
			}
		}
		
		public System.Data.Linq.Table<Ubezpieczyciele> Ubezpieczyciele
		{
			get
			{
				return this.GetTable<Ubezpieczyciele>();
			}
		}
		
		public System.Data.Linq.Table<Warsztaty> Warsztaty
		{
			get
			{
				return this.GetTable<Warsztaty>();
			}
		}
		
		public System.Data.Linq.Table<Nadwozia> Nadwozia
		{
			get
			{
				return this.GetTable<Nadwozia>();
			}
		}
		
		public System.Data.Linq.Table<Samochody> Samochody
		{
			get
			{
				return this.GetTable<Samochody>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kontakty")]
	public partial class Kontakty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CONTACT;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CONTACTChanging(int value);
    partial void OnID_CONTACTChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Kontakty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONTACT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CONTACT
		{
			get
			{
				return this._ID_CONTACT;
			}
			set
			{
				if ((this._ID_CONTACT != value))
				{
					this.OnID_CONTACTChanging(value);
					this.SendPropertyChanging();
					this._ID_CONTACT = value;
					this.SendPropertyChanged("ID_CONTACT");
					this.OnID_CONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="VarChar(30)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="VarChar(50)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(70)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ubezpieczenia")]
	public partial class Ubezpieczenia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_INSURANCE;
		
		private System.Nullable<System.DateTime> _DataRozpoczecia;
		
		private System.Nullable<System.DateTime> _DataZakonczenia;
		
		private System.Nullable<decimal> _Cena;
		
		private int _ID_CAR_fk;
		
		private System.Nullable<bool> _Archiwalny;
		
		private string _NumerPolisy;
		
		private System.Nullable<int> _ID_INSURANCE_COMPANY_fk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_INSURANCEChanging(int value);
    partial void OnID_INSURANCEChanged();
    partial void OnDataRozpoczeciaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataRozpoczeciaChanged();
    partial void OnDataZakonczeniaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataZakonczeniaChanged();
    partial void OnCenaChanging(System.Nullable<decimal> value);
    partial void OnCenaChanged();
    partial void OnID_CAR_fkChanging(int value);
    partial void OnID_CAR_fkChanged();
    partial void OnArchiwalnyChanging(System.Nullable<bool> value);
    partial void OnArchiwalnyChanged();
    partial void OnNumerPolisyChanging(string value);
    partial void OnNumerPolisyChanged();
    partial void OnID_INSURANCE_COMPANY_fkChanging(System.Nullable<int> value);
    partial void OnID_INSURANCE_COMPANY_fkChanged();
    #endregion
		
		public Ubezpieczenia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSURANCE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_INSURANCE
		{
			get
			{
				return this._ID_INSURANCE;
			}
			set
			{
				if ((this._ID_INSURANCE != value))
				{
					this.OnID_INSURANCEChanging(value);
					this.SendPropertyChanging();
					this._ID_INSURANCE = value;
					this.SendPropertyChanged("ID_INSURANCE");
					this.OnID_INSURANCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRozpoczecia", DbType="Date")]
		public System.Nullable<System.DateTime> DataRozpoczecia
		{
			get
			{
				return this._DataRozpoczecia;
			}
			set
			{
				if ((this._DataRozpoczecia != value))
				{
					this.OnDataRozpoczeciaChanging(value);
					this.SendPropertyChanging();
					this._DataRozpoczecia = value;
					this.SendPropertyChanged("DataRozpoczecia");
					this.OnDataRozpoczeciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataZakonczenia", DbType="Date")]
		public System.Nullable<System.DateTime> DataZakonczenia
		{
			get
			{
				return this._DataZakonczenia;
			}
			set
			{
				if ((this._DataZakonczenia != value))
				{
					this.OnDataZakonczeniaChanging(value);
					this.SendPropertyChanging();
					this._DataZakonczenia = value;
					this.SendPropertyChanged("DataZakonczenia");
					this.OnDataZakonczeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cena", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> Cena
		{
			get
			{
				return this._Cena;
			}
			set
			{
				if ((this._Cena != value))
				{
					this.OnCenaChanging(value);
					this.SendPropertyChanging();
					this._Cena = value;
					this.SendPropertyChanged("Cena");
					this.OnCenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CAR_fk", DbType="Int NOT NULL")]
		public int ID_CAR_fk
		{
			get
			{
				return this._ID_CAR_fk;
			}
			set
			{
				if ((this._ID_CAR_fk != value))
				{
					this.OnID_CAR_fkChanging(value);
					this.SendPropertyChanging();
					this._ID_CAR_fk = value;
					this.SendPropertyChanged("ID_CAR_fk");
					this.OnID_CAR_fkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Archiwalny", DbType="Bit")]
		public System.Nullable<bool> Archiwalny
		{
			get
			{
				return this._Archiwalny;
			}
			set
			{
				if ((this._Archiwalny != value))
				{
					this.OnArchiwalnyChanging(value);
					this.SendPropertyChanging();
					this._Archiwalny = value;
					this.SendPropertyChanged("Archiwalny");
					this.OnArchiwalnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumerPolisy", DbType="VarChar(30)")]
		public string NumerPolisy
		{
			get
			{
				return this._NumerPolisy;
			}
			set
			{
				if ((this._NumerPolisy != value))
				{
					this.OnNumerPolisyChanging(value);
					this.SendPropertyChanging();
					this._NumerPolisy = value;
					this.SendPropertyChanged("NumerPolisy");
					this.OnNumerPolisyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSURANCE_COMPANY_fk", DbType="Int")]
		public System.Nullable<int> ID_INSURANCE_COMPANY_fk
		{
			get
			{
				return this._ID_INSURANCE_COMPANY_fk;
			}
			set
			{
				if ((this._ID_INSURANCE_COMPANY_fk != value))
				{
					this.OnID_INSURANCE_COMPANY_fkChanging(value);
					this.SendPropertyChanging();
					this._ID_INSURANCE_COMPANY_fk = value;
					this.SendPropertyChanged("ID_INSURANCE_COMPANY_fk");
					this.OnID_INSURANCE_COMPANY_fkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Przeglady")]
	public partial class Przeglady : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_INSPECTION;
		
		private System.Nullable<System.DateTime> _DataRozpoczecia;
		
		private System.Nullable<System.DateTime> _DataZakonczenia;
		
		private System.Nullable<bool> _Archiwalny;
		
		private int _ID_CAR_fk;
		
		private System.Nullable<int> _ID_INSPECTION_COMPANY_fk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_INSPECTIONChanging(int value);
    partial void OnID_INSPECTIONChanged();
    partial void OnDataRozpoczeciaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataRozpoczeciaChanged();
    partial void OnDataZakonczeniaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataZakonczeniaChanged();
    partial void OnArchiwalnyChanging(System.Nullable<bool> value);
    partial void OnArchiwalnyChanged();
    partial void OnID_CAR_fkChanging(int value);
    partial void OnID_CAR_fkChanged();
    partial void OnID_INSPECTION_COMPANY_fkChanging(System.Nullable<int> value);
    partial void OnID_INSPECTION_COMPANY_fkChanged();
    #endregion
		
		public Przeglady()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSPECTION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_INSPECTION
		{
			get
			{
				return this._ID_INSPECTION;
			}
			set
			{
				if ((this._ID_INSPECTION != value))
				{
					this.OnID_INSPECTIONChanging(value);
					this.SendPropertyChanging();
					this._ID_INSPECTION = value;
					this.SendPropertyChanged("ID_INSPECTION");
					this.OnID_INSPECTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRozpoczecia", DbType="Date")]
		public System.Nullable<System.DateTime> DataRozpoczecia
		{
			get
			{
				return this._DataRozpoczecia;
			}
			set
			{
				if ((this._DataRozpoczecia != value))
				{
					this.OnDataRozpoczeciaChanging(value);
					this.SendPropertyChanging();
					this._DataRozpoczecia = value;
					this.SendPropertyChanged("DataRozpoczecia");
					this.OnDataRozpoczeciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataZakonczenia", DbType="Date")]
		public System.Nullable<System.DateTime> DataZakonczenia
		{
			get
			{
				return this._DataZakonczenia;
			}
			set
			{
				if ((this._DataZakonczenia != value))
				{
					this.OnDataZakonczeniaChanging(value);
					this.SendPropertyChanging();
					this._DataZakonczenia = value;
					this.SendPropertyChanged("DataZakonczenia");
					this.OnDataZakonczeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Archiwalny", DbType="Bit")]
		public System.Nullable<bool> Archiwalny
		{
			get
			{
				return this._Archiwalny;
			}
			set
			{
				if ((this._Archiwalny != value))
				{
					this.OnArchiwalnyChanging(value);
					this.SendPropertyChanging();
					this._Archiwalny = value;
					this.SendPropertyChanged("Archiwalny");
					this.OnArchiwalnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CAR_fk", DbType="Int NOT NULL")]
		public int ID_CAR_fk
		{
			get
			{
				return this._ID_CAR_fk;
			}
			set
			{
				if ((this._ID_CAR_fk != value))
				{
					this.OnID_CAR_fkChanging(value);
					this.SendPropertyChanging();
					this._ID_CAR_fk = value;
					this.SendPropertyChanged("ID_CAR_fk");
					this.OnID_CAR_fkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSPECTION_COMPANY_fk", DbType="Int")]
		public System.Nullable<int> ID_INSPECTION_COMPANY_fk
		{
			get
			{
				return this._ID_INSPECTION_COMPANY_fk;
			}
			set
			{
				if ((this._ID_INSPECTION_COMPANY_fk != value))
				{
					this.OnID_INSPECTION_COMPANY_fkChanging(value);
					this.SendPropertyChanging();
					this._ID_INSPECTION_COMPANY_fk = value;
					this.SendPropertyChanged("ID_INSPECTION_COMPANY_fk");
					this.OnID_INSPECTION_COMPANY_fkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RodzajePaliwa")]
	public partial class RodzajePaliwa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_FUEL;
		
		private string _RodzajPaliwa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_FUELChanging(int value);
    partial void OnID_FUELChanged();
    partial void OnRodzajPaliwaChanging(string value);
    partial void OnRodzajPaliwaChanged();
    #endregion
		
		public RodzajePaliwa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FUEL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_FUEL
		{
			get
			{
				return this._ID_FUEL;
			}
			set
			{
				if ((this._ID_FUEL != value))
				{
					this.OnID_FUELChanging(value);
					this.SendPropertyChanging();
					this._ID_FUEL = value;
					this.SendPropertyChanged("ID_FUEL");
					this.OnID_FUELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RodzajPaliwa", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string RodzajPaliwa
		{
			get
			{
				return this._RodzajPaliwa;
			}
			set
			{
				if ((this._RodzajPaliwa != value))
				{
					this.OnRodzajPaliwaChanging(value);
					this.SendPropertyChanging();
					this._RodzajPaliwa = value;
					this.SendPropertyChanged("RodzajPaliwa");
					this.OnRodzajPaliwaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Firmy")]
	public partial class Firmy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_COMPANY;
		
		private string _Firma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_COMPANYChanging(int value);
    partial void OnID_COMPANYChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    #endregion
		
		public Firmy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_COMPANY", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_COMPANY
		{
			get
			{
				return this._ID_COMPANY;
			}
			set
			{
				if ((this._ID_COMPANY != value))
				{
					this.OnID_COMPANYChanging(value);
					this.SendPropertyChanging();
					this._ID_COMPANY = value;
					this.SendPropertyChanged("ID_COMPANY");
					this.OnID_COMPANYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(50)")]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ubezpieczyciele")]
	public partial class Ubezpieczyciele : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_INSURANCE_COMPANY;
		
		private string _Firma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_INSURANCE_COMPANYChanging(int value);
    partial void OnID_INSURANCE_COMPANYChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    #endregion
		
		public Ubezpieczyciele()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSURANCE_COMPANY", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_INSURANCE_COMPANY
		{
			get
			{
				return this._ID_INSURANCE_COMPANY;
			}
			set
			{
				if ((this._ID_INSURANCE_COMPANY != value))
				{
					this.OnID_INSURANCE_COMPANYChanging(value);
					this.SendPropertyChanging();
					this._ID_INSURANCE_COMPANY = value;
					this.SendPropertyChanged("ID_INSURANCE_COMPANY");
					this.OnID_INSURANCE_COMPANYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(40)")]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Warsztaty")]
	public partial class Warsztaty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_INSPECTION_COMPANY;
		
		private string _Firma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_INSPECTION_COMPANYChanging(int value);
    partial void OnID_INSPECTION_COMPANYChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    #endregion
		
		public Warsztaty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSPECTION_COMPANY", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_INSPECTION_COMPANY
		{
			get
			{
				return this._ID_INSPECTION_COMPANY;
			}
			set
			{
				if ((this._ID_INSPECTION_COMPANY != value))
				{
					this.OnID_INSPECTION_COMPANYChanging(value);
					this.SendPropertyChanging();
					this._ID_INSPECTION_COMPANY = value;
					this.SendPropertyChanged("ID_INSPECTION_COMPANY");
					this.OnID_INSPECTION_COMPANYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nadwozia")]
	public partial class Nadwozia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_BODY;
		
		private string _Nazwa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BODYChanging(int value);
    partial void OnID_BODYChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    #endregion
		
		public Nadwozia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BODY", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_BODY
		{
			get
			{
				return this._ID_BODY;
			}
			set
			{
				if ((this._ID_BODY != value))
				{
					this.OnID_BODYChanging(value);
					this.SendPropertyChanging();
					this._ID_BODY = value;
					this.SendPropertyChanged("ID_BODY");
					this.OnID_BODYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(30)")]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Samochody")]
	public partial class Samochody : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CAR;
		
		private string _Marka;
		
		private string _Model;
		
		private string _Rocznik;
		
		private string _Rejestracja;
		
		private string _NrDowoduRejestracyjnego;
		
		private System.Nullable<System.DateTime> _DataWydaniaDowoduRejestracyjnego;
		
		private string _VIN;
		
		private System.Nullable<System.DateTime> _DataRejestracji;
		
		private string _KartaPojazdu;
		
		private System.Nullable<int> _Moc;
		
		private System.Nullable<int> _Pojemnosc;
		
		private System.Nullable<int> _MasaWlasna;
		
		private System.Nullable<int> _DMC;
		
		private System.Nullable<int> _DniDoUbezpieczenia;
		
		private System.Nullable<int> _DniDoPrzegladu;
		
		private System.Nullable<int> _ID_COMPANY_fk;
		
		private System.Nullable<int> _ID_FUEL_fk;
		
		private System.Nullable<int> _ID_BODY_fk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CARChanging(int value);
    partial void OnID_CARChanged();
    partial void OnMarkaChanging(string value);
    partial void OnMarkaChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnRocznikChanging(string value);
    partial void OnRocznikChanged();
    partial void OnRejestracjaChanging(string value);
    partial void OnRejestracjaChanged();
    partial void OnNrDowoduRejestracyjnegoChanging(string value);
    partial void OnNrDowoduRejestracyjnegoChanged();
    partial void OnDataWydaniaDowoduRejestracyjnegoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataWydaniaDowoduRejestracyjnegoChanged();
    partial void OnVINChanging(string value);
    partial void OnVINChanged();
    partial void OnDataRejestracjiChanging(System.Nullable<System.DateTime> value);
    partial void OnDataRejestracjiChanged();
    partial void OnKartaPojazduChanging(string value);
    partial void OnKartaPojazduChanged();
    partial void OnMocChanging(System.Nullable<int> value);
    partial void OnMocChanged();
    partial void OnPojemnoscChanging(System.Nullable<int> value);
    partial void OnPojemnoscChanged();
    partial void OnMasaWlasnaChanging(System.Nullable<int> value);
    partial void OnMasaWlasnaChanged();
    partial void OnDMCChanging(System.Nullable<int> value);
    partial void OnDMCChanged();
    partial void OnDniDoUbezpieczeniaChanging(System.Nullable<int> value);
    partial void OnDniDoUbezpieczeniaChanged();
    partial void OnDniDoPrzegladuChanging(System.Nullable<int> value);
    partial void OnDniDoPrzegladuChanged();
    partial void OnID_COMPANY_fkChanging(System.Nullable<int> value);
    partial void OnID_COMPANY_fkChanged();
    partial void OnID_FUEL_fkChanging(System.Nullable<int> value);
    partial void OnID_FUEL_fkChanged();
    partial void OnID_BODY_fkChanging(System.Nullable<int> value);
    partial void OnID_BODY_fkChanged();
    #endregion
		
		public Samochody()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CAR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CAR
		{
			get
			{
				return this._ID_CAR;
			}
			set
			{
				if ((this._ID_CAR != value))
				{
					this.OnID_CARChanging(value);
					this.SendPropertyChanging();
					this._ID_CAR = value;
					this.SendPropertyChanged("ID_CAR");
					this.OnID_CARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marka", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Marka
		{
			get
			{
				return this._Marka;
			}
			set
			{
				if ((this._Marka != value))
				{
					this.OnMarkaChanging(value);
					this.SendPropertyChanging();
					this._Marka = value;
					this.SendPropertyChanged("Marka");
					this.OnMarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarChar(50)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rocznik", DbType="VarChar(4)")]
		public string Rocznik
		{
			get
			{
				return this._Rocznik;
			}
			set
			{
				if ((this._Rocznik != value))
				{
					this.OnRocznikChanging(value);
					this.SendPropertyChanging();
					this._Rocznik = value;
					this.SendPropertyChanged("Rocznik");
					this.OnRocznikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rejestracja", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Rejestracja
		{
			get
			{
				return this._Rejestracja;
			}
			set
			{
				if ((this._Rejestracja != value))
				{
					this.OnRejestracjaChanging(value);
					this.SendPropertyChanging();
					this._Rejestracja = value;
					this.SendPropertyChanged("Rejestracja");
					this.OnRejestracjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrDowoduRejestracyjnego", DbType="VarChar(25)")]
		public string NrDowoduRejestracyjnego
		{
			get
			{
				return this._NrDowoduRejestracyjnego;
			}
			set
			{
				if ((this._NrDowoduRejestracyjnego != value))
				{
					this.OnNrDowoduRejestracyjnegoChanging(value);
					this.SendPropertyChanging();
					this._NrDowoduRejestracyjnego = value;
					this.SendPropertyChanged("NrDowoduRejestracyjnego");
					this.OnNrDowoduRejestracyjnegoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataWydaniaDowoduRejestracyjnego", DbType="Date")]
		public System.Nullable<System.DateTime> DataWydaniaDowoduRejestracyjnego
		{
			get
			{
				return this._DataWydaniaDowoduRejestracyjnego;
			}
			set
			{
				if ((this._DataWydaniaDowoduRejestracyjnego != value))
				{
					this.OnDataWydaniaDowoduRejestracyjnegoChanging(value);
					this.SendPropertyChanging();
					this._DataWydaniaDowoduRejestracyjnego = value;
					this.SendPropertyChanged("DataWydaniaDowoduRejestracyjnego");
					this.OnDataWydaniaDowoduRejestracyjnegoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIN", DbType="VarChar(17)")]
		public string VIN
		{
			get
			{
				return this._VIN;
			}
			set
			{
				if ((this._VIN != value))
				{
					this.OnVINChanging(value);
					this.SendPropertyChanging();
					this._VIN = value;
					this.SendPropertyChanged("VIN");
					this.OnVINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRejestracji", DbType="Date")]
		public System.Nullable<System.DateTime> DataRejestracji
		{
			get
			{
				return this._DataRejestracji;
			}
			set
			{
				if ((this._DataRejestracji != value))
				{
					this.OnDataRejestracjiChanging(value);
					this.SendPropertyChanging();
					this._DataRejestracji = value;
					this.SendPropertyChanged("DataRejestracji");
					this.OnDataRejestracjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KartaPojazdu", DbType="VarChar(30)")]
		public string KartaPojazdu
		{
			get
			{
				return this._KartaPojazdu;
			}
			set
			{
				if ((this._KartaPojazdu != value))
				{
					this.OnKartaPojazduChanging(value);
					this.SendPropertyChanging();
					this._KartaPojazdu = value;
					this.SendPropertyChanged("KartaPojazdu");
					this.OnKartaPojazduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moc", DbType="Int")]
		public System.Nullable<int> Moc
		{
			get
			{
				return this._Moc;
			}
			set
			{
				if ((this._Moc != value))
				{
					this.OnMocChanging(value);
					this.SendPropertyChanging();
					this._Moc = value;
					this.SendPropertyChanged("Moc");
					this.OnMocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pojemnosc", DbType="Int")]
		public System.Nullable<int> Pojemnosc
		{
			get
			{
				return this._Pojemnosc;
			}
			set
			{
				if ((this._Pojemnosc != value))
				{
					this.OnPojemnoscChanging(value);
					this.SendPropertyChanging();
					this._Pojemnosc = value;
					this.SendPropertyChanged("Pojemnosc");
					this.OnPojemnoscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasaWlasna", DbType="Int")]
		public System.Nullable<int> MasaWlasna
		{
			get
			{
				return this._MasaWlasna;
			}
			set
			{
				if ((this._MasaWlasna != value))
				{
					this.OnMasaWlasnaChanging(value);
					this.SendPropertyChanging();
					this._MasaWlasna = value;
					this.SendPropertyChanged("MasaWlasna");
					this.OnMasaWlasnaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMC", DbType="Int")]
		public System.Nullable<int> DMC
		{
			get
			{
				return this._DMC;
			}
			set
			{
				if ((this._DMC != value))
				{
					this.OnDMCChanging(value);
					this.SendPropertyChanging();
					this._DMC = value;
					this.SendPropertyChanged("DMC");
					this.OnDMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DniDoUbezpieczenia", DbType="Int")]
		public System.Nullable<int> DniDoUbezpieczenia
		{
			get
			{
				return this._DniDoUbezpieczenia;
			}
			set
			{
				if ((this._DniDoUbezpieczenia != value))
				{
					this.OnDniDoUbezpieczeniaChanging(value);
					this.SendPropertyChanging();
					this._DniDoUbezpieczenia = value;
					this.SendPropertyChanged("DniDoUbezpieczenia");
					this.OnDniDoUbezpieczeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DniDoPrzegladu", DbType="Int")]
		public System.Nullable<int> DniDoPrzegladu
		{
			get
			{
				return this._DniDoPrzegladu;
			}
			set
			{
				if ((this._DniDoPrzegladu != value))
				{
					this.OnDniDoPrzegladuChanging(value);
					this.SendPropertyChanging();
					this._DniDoPrzegladu = value;
					this.SendPropertyChanged("DniDoPrzegladu");
					this.OnDniDoPrzegladuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_COMPANY_fk", DbType="Int")]
		public System.Nullable<int> ID_COMPANY_fk
		{
			get
			{
				return this._ID_COMPANY_fk;
			}
			set
			{
				if ((this._ID_COMPANY_fk != value))
				{
					this.OnID_COMPANY_fkChanging(value);
					this.SendPropertyChanging();
					this._ID_COMPANY_fk = value;
					this.SendPropertyChanged("ID_COMPANY_fk");
					this.OnID_COMPANY_fkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FUEL_fk", DbType="Int")]
		public System.Nullable<int> ID_FUEL_fk
		{
			get
			{
				return this._ID_FUEL_fk;
			}
			set
			{
				if ((this._ID_FUEL_fk != value))
				{
					this.OnID_FUEL_fkChanging(value);
					this.SendPropertyChanging();
					this._ID_FUEL_fk = value;
					this.SendPropertyChanged("ID_FUEL_fk");
					this.OnID_FUEL_fkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BODY_fk", DbType="Int")]
		public System.Nullable<int> ID_BODY_fk
		{
			get
			{
				return this._ID_BODY_fk;
			}
			set
			{
				if ((this._ID_BODY_fk != value))
				{
					this.OnID_BODY_fkChanging(value);
					this.SendPropertyChanging();
					this._ID_BODY_fk = value;
					this.SendPropertyChanged("ID_BODY_fk");
					this.OnID_BODY_fkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
